import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const avenirMedium = localFont({
  src: "./fonts/Avenir-Roman.ttf",
  variable: "--font-avenir-light",
  weight: "500", // Medium weight
});
const avenirHeavy = localFont({
  src: "./fonts/Avenir-Heavy.ttf",
  variable: "--font-avenir-heavy",
  weight: "500", // Medium weight
});
const lorettaLight = localFont({
  src: "./fonts/fonnts.com-Loretta-Display.otf",
  variable: "--fonnts-com-Loretta-Light",
  weight: "500", // Medium weight
});
const newTimesRomanBold = localFont({
  src: "./fonts/times new roman bold.ttf",
  variable: "--fonts-new-times-roman-bold",
  weight: "500", // Medium weight
});
const newTimesRomanLight = localFont({
  src: "./fonts/times new roman.ttf",
  variable: "--fonts-new-times-roman-light",
  weight: "500", // Medium weight
});

export const metadata: Metadata = {
  title: "Aurtel Consulting Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="customtheme" >
      <head>
        {/* PWA Metadata */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#312e81" />
        <link rel="icon" href="/icons/icon-192x192.png" />
        <meta name="description" content="Your PWA Description" />
      </head>
      <body
        className={`${avenirMedium.variable} ${lorettaLight.variable} ${avenirHeavy.variable} ${newTimesRomanLight.variable} ${newTimesRomanBold.variable} antialiased`}
      >
        <Navbar />
        <main> {children}</main>
        <Footer/>
      </body>
    </html>
  );
}
