import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Aurtel Consulting Group",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <h1>Home page here</h1>
    </div>
  );
}

export default page