import { Metadata } from "next";
import HomeView from "@/view/HomeView";

export const metadata: Metadata = {
  title: "Aurtel Consulting Group",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <HomeView/>
    </div>
  );
}

export default page