import HomeView from "@/view/HomeView";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Aurtel Consulting Group",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <HomeView/>
    </div>
  );
}

export default page